[profile.default]
src = "src"
out = "out"
test = 'test'
libs = ["lib"]
gas_reports = ["BootcampFactory", "DepositHandler"]

remappings = [
    'openzeppelin/=lib/openzeppelin-contracts/',
    'forge-std/=lib/forge-std/src'
]